/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}
